config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :usparams
  resources :products

  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :usparam
  has_many :products
end

app/models/usparam.rb
class Usparam < ApplicationRecord
  belongs_to :user
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    validates :firstname, presence: true
    validates :lastname, presence: true
    validates :age, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @prods = Product.all
  end

    def new
      @prod = Product.new
    end

    def create
      @prod = current_user.products.build(prod_params)
      if @prod.save
        redirect_to root_path
      else
        flash[:error] = "Post has error"
        render 'new'
      end
    end


    def destroy
      @prod.destroy
      redirect_to root_path
    end

  private

    def prod_params
      params.require(:product).permit(:user_id, :title, :description, :price)
    end
end

app/controllers/usparams_controller.rb
class UsparamsController < ApplicationController
    def new
      @param = Usparam.new
    end

    def create
      @param = current_user.build_usparam(param_params)
      if @param.save
        redirect_to root_path
      else
        flash[:error] = "User param has error"
        render 'new'
      end
    end

    def edit
      @param = current_user.usparam
    end

    def update
      @param = Usparam.find_by(user_id: current_user.id)
      if @param.update(param_params)
        flash[:notice] = "User param successfully updated"
        redirect_to usparam_path(@param.id)
      else
        flash[:error] = "User param has error"
        render 'edit'
      end
    end

    def show
      @param = Usparam.find_by(user_id: current_user.id)
    end

  private

    def param_params
      params.require(:usparam).permit(:user_id, :firstname, :lastname, :age, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/usparams_helper.rb
module UsparamsHelper
end

app/views/layouts/_header.html.erb
<%= link_to "Home", root_path %>
<% if !user_signed_in? %>
<%= link_to "Login or sign up", new_user_session_path %>
<% else %>
<%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% if current_user.usparam.nil? %>
     <%= link_to "Profile", new_usparam_path %>
  <% else %>
   <%= link_to "Profile", usparam_path(current_user.id) %>
  <% end %>
  <%= link_to "Add product", new_product_path %>
<%end%>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catalog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Catalog</h1>
<% if @prods == [] %>
    <p>No products yet</p>
<% else %>
  <%= @prods.each do |p| %>
    <p>
      <big><%= p.title %></big><br>
      <%= p.description %><br>
      <%= p.price %><br>
    </p>
  <% end %>
<% end %>

app/views/products/new.html.erb
<% if @prod.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@prod.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @prod.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @prod, url: products_path do |f| %>
  Title: <%= f.text_field :title %><br />
  <%= f.text_area :description, size: "60x12" %><br />
  Price: <%= f.number_field :price %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/usparams/edit.html.erb
<% if @param.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@param.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @param.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @param, url: usparam_path(current_user.id) do |f| %>

  Firsname: <%= f.text_field :firstname %><br />
  Lastname: <%= f.text_field :lastname %><br />
  Age: <%= f.number_field :age %><br />
  Avatar: <%= f.file_field :avatar %><br />

  <%= f.submit "Update" %>
<% end %>

app/views/usparams/new.html.erb
<% if @param.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@param.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @param.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @param, url: usparams_path do |f| %>
  Firsname: <%= f.text_field :firstname %><br />
  Lastname: <%= f.text_field :lastname %><br />
  Age: <%= f.number_field :age %><br />
  Avatar: <%= f.file_field :avatar %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/usparams/show.html.erb
<%= image_tag @param.avatar.url(:medium) %>
<br>
Firstname: <%= current_user.usparam.firstname %><br />
Lastname: <%= current_user.usparam.lastname %><br />
Age: <%= current_user.usparam.age %><br />
<%= link_to "edit", edit_usparam_path(current_user.id) %><br />